### ISSUE TITLE
Cleanup 

### ISSUE THREAD

**Issue by JulesKhong** [thinkshout/ts_motif#12]
After using ts_motif on CSIS, and now setting it up on another site, there are a few things that can be cleaned up. 

This ticket:
- [x] Updates line height variables to clearer names (`lh-10` instead of `lineheight-snug`)
- [x] Moves style guide sections into included templates, so it's more modular
- [x] Updates style guide classes, so it's easier to update once a site's tokens have changed. 
- [x] Removes starter typography styles, but includes the first one to get started
- [x] Removes font sizes as tokens
- [x] Updates `z-index-1` to `z-1` for z-index tokens
- [x] Removes Motif graphic from the docs sections in base css files
- [x] Updates base friendly, unfriendly styles lean more on Tailwind -- shorter
- [x] Updates base grid styles to lean more on Tailwind -- shorter
- [x] removes the .site-container class since we can use the Tailwind provided `container` with `p-site` for site padding. 
- [x] replaces `.content-side-padding` with `p-site`
- [x] Removes opacity tokens
- [x] Removes grid tokens. eg: You can use .gap-md instead of setting a new value for the gap. 
- [x] removes font sizes as tokens.

**Comment by mariacha** [comment]
Merged the PR. Closing
